language: python
python:
 - "3.8"

install:
 - pip3 install -r requirements.txt

script:
 - python -m black . --check
 - flake8 .
 - coverage run --source={something}

after_script:
 - python -m coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: "us-west-2"
    app: "django-tutorial"
    env: "django-env"
    bucket_name: "the-target-S3-bucket"
    on:
      all_branches: true
