language: python
python:
 - "3.8"

install:
 - pip install -r requirements.txt

script:
 - python -m black . --check
 - flake8 .
 - coverage run --source={something}

after_script:
 - python -m coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: "us-west-2"
    app: "django-tutorial"
    env: "django-env"
    bucket_name: "elasticbeanstalk-us-west-2-675072016824"
    on:
      all_branches: true
